title: Premature Optimization
subtitle: "Do you abandon science to preserve your heart, or abandon your heart and sacrifice yourself to science"
pygments: true

author:
  name: Jordan Fish
  email: jrdn.fish@gmail.com
  github: fishjord
  twitter: fishjord